/*******************************************************************************
//    Shubha Downloader
//    Shubha Downloader downloads end of day pricing data from publicly available
//    sites and converts it in different formats.
//
//    Copyright (C) 2013 Shubhalabha.in
//    Info: webmaster@shubhalabha.in
//    Contributors: jayant@xnetindia.com,
//		    prashant@xnetindia.com,
//		    anand@xnetindia.com
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//    GNU General Public License for more details.
//
//    Permission is hereby granted, free of charge, to any person obtaining a
//    copy of this software and associated documentation files (the
//    "Software"), to deal in the Software without restriction, including
//    without limitation the rights to use, copy, modify, merge copies of the Software, and to permit
//    persons to whom the Software is furnished to do so, subject to the
//    following conditions:
//    The above copyright notice and this permission notice shall be included
//    in all copies or substantial portions of the Software.
//    The name of software can not changed. Software can not be sold in any manner.
//
//    You should have received a copy of the GNU General Public License
//    along with this program. If not, see <http://www.gnu.org/licenses/>
//
//    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
//    OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
//    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
//    NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
//    DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
//    OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
//    USE OR OTHER DEALINGS IN THE SOFTWARE.
********************************************************************************/
var http=require("http"),fs=require("fs"),request=require("request"),AdmZip=require("adm-zip");function loadevent(a,b){Ext.getCmp("pbar3").updateText("Processing started please wait . . .");Ext.getCmp("pbar3").updateProgress(0.002);var d=[],k=require("ya-csv"),l=k.createCsvFileReader("baseurl.csv",{separator:","});l.addListener("data",function(a){d.push(a)});l=k.createCsvFileReader("settings.csv",{separator:","});l.addListener("data",function(k){d.push(k);"options"==k[0]&&download(a,b,d)})}
function downloadseclist(a,b){require("http");var d=require("fs"),k=require("request");k({method:"GET",uri:"http://www.nseindia.com/content/equities/sec_list.csv",headers:{"User-Agent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",Referer:"http://www.nseindia.com/products/content/all_daily_reports.htm","Accept-Encoding":"gzip,deflate,sdch",Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",Cookie:"cookie"}},function(l,
p){if(200==p.statusCode){var g=d.createWriteStream(a+"sec_list.csv"),f=k({method:"GET",uri:"http://www.nseindia.com/content/equities/sec_list.csv",headers:{"User-Agent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",Referer:"http://www.nseindia.com/products/content/all_daily_reports.htm","Accept-Encoding":"gzip,deflate,sdch",Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",Cookie:"cookie"}});f.pipe(g);f.on("end",function(){document.getElementById("om").innerHTML+=
"<br/>sec_list is downloaded";addlog(b,"sec_list is downloaded")})}else document.getElementById("om").innerHTML+="<br/><font color=red>sec_list.csv  is not on server</font>",addlog(b,"sec_list.csv  is not on server")});return!0}
function download(a,b,d){Ext.getCmp("pbar3").updateText("Processing started please wait . . .");Ext.getCmp("pbar3").updateProgress(0.004);document.getElementById("om").innerHTML="loading...";for(var k=0;k<d.length;k++)"datafolder"==d[k].toString().split(",")[0]&&makedir(d[k].toString().split(",")[1],d,a,b)}
function downloadfiles(a,b,d,k,l,p,g,f,h){try{var c=a[b].split("-")[0],e=a[b].split("-")[1],j=a[b].split("-")[2],m=a[b].split("-")[3];m.substr(2,2);var n=c.toUpperCase();Ext.getCmp("pbar3").updateText("cm"+j+n+m+"bhav.csv.zip downloading. . .");Ext.getCmp("pbar3").updateProgress(0.2);for(var r="",c=0;c<d.length;c++)"nsecmbhavcopy"==d[c].toString().split(",")[0]&&(r=d[c].toString().split(",")[1]+m+"/"+n+"/cm"+j+""+n+""+m+"bhav.csv.zip");require("url");require("http");var q=require("fs"),s=require("adm-zip"),
u=require("request");u({method:"GET",uri:r,headers:{"User-Agent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",Referer:"http://www.nseindia.com/products/content/all_daily_reports.htm","Accept-Encoding":"gzip,deflate,sdch",Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",Cookie:"cookie"}},function(a,b){null!=b?null!=b.statusCode||""!=b.statusCode?!a&&200==b.statusCode?t(b.statusCode):t(404):t(404):t(404)});var t=function(c){if(200==
c){Ext.getCmp("pbar3").updateText("cm"+j+n+m+"bhav.csv.zip dwonloading started . . .");Ext.getCmp("pbar3").updateProgress(0.4);c=q.createWriteStream(k+"cm"+j+n+m+"bhav.csv.zip");var e=u({method:"GET",uri:r,headers:{"User-Agent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",Referer:"http://www.nseindia.com/products/content/all_daily_reports.htm","Accept-Encoding":"gzip,deflate,sdch",encoding:"null",Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*//*;q=0.8",
Cookie:"cookie"}});e.on("error",function(){document.getElementById("om").innerHTML+="<br/>Error occured in downloading cm"+j+n+m+"bhav.csv.zip";addlog(g,"Error occured in downloading cm"+j+n+m+"bhav.csv.zip");setTimeout(function(){downloadfiles(a,b,d,k,l,p,g,f,h)},1E3)});e.pipe(c);e.on("end",function(){Ext.getCmp("pbar3").updateText("cm"+j+n+m+"bhav.csv.zip is downloaded. . .");Ext.getCmp("pbar3").updateProgress(0.8);document.getElementById("om").innerHTML+="<br>cm"+j+n+m+"bhav.csv.zip is downloaded...";
addlog(g,"cm"+j+n+m+"bhav.csv.zip is downloaded");(new s(k+"cm"+j+n+m+"bhav.csv.zip")).extractAllTo(l,!0);Ext.getCmp("pbar3").updateText("cm"+j+n+m+"bhav.csv.zip is extracted. . .");Ext.getCmp("pbar3").updateProgress(1);document.getElementById("om").innerHTML+="<br>cm"+j+n+m+"bhav.csv.zip is extracted...";addlog(g,"cm"+j+n+m+"bhav.csv.zip is extracted");b++;a.length>b?setTimeout(function(){downloadfiles(a,b,d,k,l,p,g,f,h)},1E3):downloadmto(a,0,d,k,l,p,g,f,h)})}else document.getElementById("om").innerHTML+=
"<br/><font color=red>cm"+j+n+m+"bhav.csv.zip is not present on server</font>",addlog(g,"cm"+j+n+m+"bhav.csv.zip is not present on server"),b++,a.length>b?setTimeout(function(){downloadfiles(a,b,d,k,l,p,g,f,h)},1E3):downloadmto(a,0,d,k,l,p,g,f,h)}}catch(v){document.getElementById("om").innerHTML+="<br/>File is not found for this date: "+j+e+m,addlog(g,"File is not found for this date: "+j+e+m),setTimeout(function(){downloadfiles(a,b,d,k,l,p,g,f,h)},1E3)}}
function performtask(a,b,d,k,l,p,g){var f=new Date,h=require("fs"),c=f.getTime().toString()+".txt";h.writeFile(l+c,"log date:-"+f+"\n",function(a){a&&a&&(document.getElementById("om").innerHTML+="<br/>"+a)});l+=c;Ext.getCmp("pbar3").updateText("Processing started please wait . . .");Ext.getCmp("pbar3").updateProgress(0.006);var e=p.split("/"),j=g.split("/"),m=[];$(document).ready(function(){for(var a=new Date(e[0]+","+e[1]+","+e[2]),b=new Date(j[0]+","+j[1]+","+j[2]),d,g;a<=b;){if(!a.toDateString().match("Sat")&&
!a.toDateString().match("Sun")){d=10>a.getMonth()+1?"0"+(a.getMonth()+1):a.getMonth()+1;g=10>a.getDate()?"0"+a.getDate():a.getDate();var c,h;c=a.toDateString().split(" ")[1];h=a.getFullYear();m.push(c+"-"+d+"-"+g+"-"+h)}a.setTime(a.getTime()+864E5)}});0<m.length?(Ext.getCmp("pbar3").updateText("Cash Market dwonloading is started . . ."),Ext.getCmp("pbar3").updateProgress(0.02),downloadseclist(b,l),downloadfiles(m,0,a,b,d,k,l,p,g)):$("#p3").hide()}
function getmonth(a){switch(parseInt(a)){case 1:a="JAN";break;case 2:a="FEB";break;case 3:a="MAR";break;case 4:a="APR";break;case 5:a="MAY";break;case 6:a="JUN";break;case 7:a="JUL";break;case 8:a="AUG";break;case 9:a="SEP";break;case 10:a="OCT";break;case 11:a="NOV";break;case 12:a="DEC"}return a}
function getMonth(a){switch(a.toUpperCase()){case "JAN":a="01";break;case "FEB":a="02";break;case "MAR":a="03";break;case "APR":a="04";break;case "MAY":a="05";break;case "JUN":a="06";break;case "JUL":a="07";break;case "AUG":a="08";break;case "SEP":a="09";break;case "OCT":a="10";break;case "NOV":a="11";break;case "DEC":a="12"}return a}
function downloadmto(a,b,d,k,l,p,g,f,h){function c(c){var e=require("fs");200==c?(Ext.getCmp("pbar3").updateText("MTO_"+m+""+j+""+n+".DAT downloading started. . ."),Ext.getCmp("pbar3").updateProgress(0.4),c=e.createWriteStream(k+"MTO_"+m+""+j+""+n+".DAT"),e=q({method:"GET",uri:r,headers:{"User-Agent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",Referer:"http://www.nseindia.com/products/content/all_daily_reports.htm","Accept-Encoding":"gzip,deflate,sdch",
Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",Cookie:"cookie"}}),e.on("error",function(){document.getElementById("om").innerHTML+="<br/>Error occured in downloading MTO_"+m+""+j+""+n+".DAT";addlog(g,"Error occured in downloading MTO_"+m+""+j+""+n+".DAT");setTimeout(function(){downloadmto(a,b,d,k,l,p,g,f,h)},1E3)}),e.pipe(c),e.on("end",function(){Ext.getCmp("pbar3").updateText("MTO_"+m+""+j+""+n+".DAT download completed. . .");Ext.getCmp("pbar3").updateProgress(1);document.getElementById("om").innerHTML+=
"<br>MTO_"+m+""+j+""+n+".DAT is downloaded ..";addlog(g,"MTO_"+m+""+j+""+n+".DAT is downloaded ..");b++;a.length>b?setTimeout(function(){downloadmto(a,b,d,k,l,p,g,f,h)},1E3):download_przip(a,0,d,k,l,p,g,f,h)})):(document.getElementById("om").innerHTML+="<br/><font color=red>MTO_"+m+""+j+""+n+".DAT is not present on server</font>",addlog(g,"MTO_"+m+""+j+""+n+".DAT is not present on server"),b++,a.length>b?setTimeout(function(){downloadmto(a,b,d,k,l,p,g,f,h)},1E3):download_przip(a,0,d,k,l,p,g,f,h))}
var e=a[b].split("-")[0],j=a[b].split("-")[1],m=a[b].split("-")[2],n=a[b].split("-")[3];n.substr(2,2);e.toUpperCase();Ext.getCmp("pbar3").updateText("MTO_"+m+""+j+""+n+".DAT downloading. . .");Ext.getCmp("pbar3").updateProgress(0.02);for(var r="",e=0;e<d.length;e++)"nsemto"==d[e].toString().split(",")[0]&&(r=d[e].toString().split(",")[1]+"MTO_"+m+""+j+""+n+".DAT");var q=require("request");q({method:"GET",uri:r,headers:{"User-Agent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",
Referer:"http://www.nseindia.com/products/content/all_daily_reports.htm","Accept-Encoding":"gzip,deflate,sdch",Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",Cookie:"cookie"}},function(a,b){null!=b?null!=b.statusCode||""!=b.statusCode?!a&&200==b.statusCode?c(b.statusCode):c(404):c(404):c(404)})}
function download_przip(a,b,d,k,l,p,g,f,h){try{var c=a[b].split("-")[0],e=a[b].split("-")[1],j=a[b].split("-")[2],m=a[b].split("-")[3],n=m.substr(2,2);c.toUpperCase();Ext.getCmp("pbar3").updateText("PR"+j+e+n+".zip is downloading. . .");Ext.getCmp("pbar3").updateProgress(0.1);document.getElementById("om").innerHTML+="<br/>PR"+j+e+n+".zip is downloading..";for(var r,c=0;c<d.length;c++)"nseprbhavcopy"==d[c].toString().split(",")[0]&&(r=d[c].toString().split(",")[1]+"PR"+j+e+n+".zip");require("url");
require("http");var q=require("fs"),s=require("adm-zip"),u=require("request");u({method:"GET",uri:r,headers:{"User-Agent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",Referer:"http://www.nseindia.com/products/content/all_daily_reports.htm","Accept-Encoding":"gzip,deflate,sdch",Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",Cookie:"cookie"}},function(a,b){null!=b?null!=b.statusCode||""!=b.statusCode?!a&&200==b.statusCode?
t(b.statusCode):t(404):t(404):t(404)});var t=function(c){for(var t=0;t<d.length;t++)"options"==d[t].toString().split(",")[0]&&d[t].toString().split(",");200==c?(Ext.getCmp("pbar3").updateText("PR"+j+e+n+".zip is downloading started. . ."),Ext.getCmp("pbar3").updateProgress(0.5),c=q.createWriteStream(k+"PR"+j+e+n+".zip"),t=u({method:"GET",uri:r,headers:{"User-Agent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",Referer:"http://www.nseindia.com/products/content/all_daily_reports.htm",
"Accept-Encoding":"gzip,deflate,sdch",encoding:"null",Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*//*;q=0.8",Cookie:"cookie"}}),t.on("error",function(){document.getElementById("om").innerHTML+="<br/>Error occured in downloading PR"+j+e+n+".zip";addlog(g,"Error occured in downloading PR"+j+e+n+".zip");download_przip(a,b,d,k,l,p,g,f,h)}),t.pipe(c),t.on("end",function(){Ext.getCmp("pbar3").updateText("PR"+j+e+n+".zip is downloaded. . .");Ext.getCmp("pbar3").updateProgress(0.7);document.getElementById("om").innerHTML+=
"<br>PR"+j+e+n+".zip is downloaded...";addlog(g,"PR"+j+e+n+".zip is downloaded...");var c=new s(k+"PR"+j+e+n+".zip");c.extractAllTo(l,!0);Ext.getCmp("pbar3").updateText("PR"+j+e+n+".zip is extracting. . .");Ext.getCmp("pbar3").updateProgress(0.8);document.getElementById("om").innerHTML+="<br>PR"+j+e+n+".zip is extracted...";addlog(g,"PR"+j+e+n+".zip is extracted...");q.existsSync(l+"fo"+j+e+m+".zip")&&(c=new s(l+"fo"+j+e+m+".zip"),c.extractAllTo(l+"unzip1/",!0));q.existsSync(l+"cd"+j+e+m+".zip")&&
(c=new s(l+"cd"+j+e+m+".zip"),c.extractAllTo(l+"unzip1/",!0),Ext.getCmp("pbar3").updateText("PR"+j+e+n+".zip is extracted. . ."),Ext.getCmp("pbar3").updateProgress(1));b++;a.length>b?setTimeout(function(){download_przip(a,b,d,k,l,p,g,f,h)},1E3):process_nse(a,0,d,k,l,p,g,f,h)})):(document.getElementById("om").innerHTML+="<br/><font color=red>PR"+e+j+n+".zip is not present on server</font>",addlog(g,"PR"+e+j+n+".zip is not present on server"),b++,a.length>b?setTimeout(function(){download_przip(a,b,
d,k,l,p,g,f,h)},1E3):process_nse(a,0,d,k,l,p,g,f,h))}}catch(v){document.getElementById("om").innerHTML+="<br/>File is not found for this date: <br/>"+v,setTimeout(function(){download_przip(a,b,d,k,l,p,g,f,h)},1E3)}}
function download_nse_cmbnd_rpt_zip(a,b,d,k,l,p,g){try{var f=a[b].split("-")[0],h=a[b].split("-")[1],c=a[b].split("-")[2],e=a[b].split("-")[3];e.substr(2,2);f.toUpperCase();document.getElementById("om").innerHTML+="<br/>combined_report"+c+h+e+".zip is downloading..";for(var j,f=0;f<d.length;f++)"nsecmbndrpt"==d[f].toString().split(",")[0]&&(j=d[f].toString().split(",")[1]+"combined_report"+c+h+e+".zip");require("url");require("http");var m=require("fs"),n=require("adm-zip"),r=require("request");r({method:"GET",
uri:j,headers:{"User-Agent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",Referer:"http://www.nseindia.com/products/content/all_daily_reports.htm","Accept-Encoding":"gzip,deflate,sdch",Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",Cookie:"cookie"}},function(a,b){null!=b?null!=b.statusCode||""!=b.statusCode?!a&&200==b.statusCode?q(b.statusCode):q(404):q(404):q(404)});var q=function(f){if(200==f){f=m.createWriteStream(k+
"combined_report"+c+h+e+".zip");var q=r({method:"GET",uri:j,headers:{"User-Agent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",Referer:"http://www.nseindia.com/products/content/all_daily_reports.htm","Accept-Encoding":"gzip,deflate,sdch",encoding:"null",Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*//*;q=0.8",Cookie:"cookie"}});q.on("error",function(){document.getElementById("om").innerHTML+="<br/>Error occured in downloading combined_report"+
c+h+e+".zip";addlog(g,"Error occured in downloading combined_report"+c+h+e+".zip");setTimeout(function(){download_nse_cmbnd_rpt_zip(a,b,d,k,l,p,g)},1E3)});q.pipe(f);q.on("end",function(){document.getElementById("om").innerHTML+="<br>combined_report"+c+h+e+".zip is downloaded...";addlog(g,"combined_report"+c+h+e+".zip is downloaded...");var j=new n(k+"combined_report"+c+h+e+".zip"),f=p.replace(/std_csv/g,"reports");j.extractAllTo(l,!0);document.getElementById("om").innerHTML+="<br>combined_report"+
c+h+e+".zip is extracted...";addlog(g,"combined_report"+c+h+e+".zip is extracted...");m.createReadStream(l+"combined_report"+c+h+e+".xls").pipe(m.createWriteStream(f+"combined_report"+c+h+e+".xls"));document.getElementById("om").innerHTML+="<br>combined_report"+c+h+e+".xls is processed...";addlog(g,"combined_report"+c+h+e+".xls is processed...");b++;a.length>b?setTimeout(function(){download_nse_cmbnd_rpt_zip(a,b,d,k,l,p,g)},1E3):Ext.getCmp("pbar3").updateProgress(0)})}else document.getElementById("om").innerHTML+=
"<br/><font color=red>combined_report"+c+h+e+".zip is not present on server</font>",addlog(g,"combined_report"+c+h+e+".zip is not present on server"),b++,a.length>b?setTimeout(function(){download_nse_cmbnd_rpt_zip(a,b,d,k,l,p,g)},1E3):Ext.getCmp("pbar3").updateProgress(0)}}catch(s){document.getElementById("om").innerHTML+="<br/>File is not found for this date: <br/>"+s,addlog(g,"File is not found for this date: <br/>"+s),setTimeout(function(){download_nse_cmbnd_rpt_zip(a,b,d,k,l,p,g)},1E3)}}
function download_bseequity(a,b,d,k,l,p,g){try{var f=a[b].split("-")[0],h=a[b].split("-")[1],c=a[b].split("-")[2],e=a[b].split("-")[3],j=e.substr(2,2);f.toUpperCase();for(var m="",f=0;f<d.length;f++)"bseequity"==d[f].toString().split(",")[0]&&(m=d[f].toString().split(",")[1]+"eq"+c+h+j+"_csv.zip");require("url");require("http");var n=require("fs"),r=require("adm-zip"),q=require("request");q({method:"GET",uri:m,headers:{"User-Agent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",
Referer:"http://www.bseindia.com/markets/equity/EQReports/BhavCopyDebt.aspx?expandable=3","Accept-Encoding":"gzip,deflate,sdch",Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",Cookie:"cookie"}},function(a,b){null!=b?null!=b.statusCode||""!=b.statusCode?!a&&200==b.statusCode?s(b.statusCode):s(404):s(404):s(404)});var s=function(e){if(200==e){e=n.createWriteStream(k+"eq"+c+h+j+"_csv.zip");var f=q({method:"GET",uri:m,headers:{"User-Agent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",
Referer:"http://www.nseindia.com/products/content/all_daily_reports.htm","Accept-Encoding":"gzip,deflate,sdch",encoding:"null",Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*//*;q=0.8",Cookie:"cookie"}});f.on("error",function(){document.getElementById("om").innerHTML+="<br/>Error occured in downloading eq"+c+h+j+"_csv.zip";addlog(g,"Error occured in downloading eq"+c+h+j+"_csv.zip");setTimeout(function(){download_bseequity(a,b,d,k,l,p,g)},1E3)});f.pipe(e);f.on("end",function(){document.getElementById("om").innerHTML+=
"<br>eq"+c+h+j+"_csv.zip is downloaded...";addlog(g,"eq"+c+h+j+"_csv.zip  is downloaded..");(new r(k+"eq"+c+h+j+"_csv.zip")).extractAllTo(l,!0);document.getElementById("om").innerHTML+="<br>eq"+c+h+j+"_csv.zip is extracted...";addlog(g,"eq"+c+h+j+"_csv.zip is extracted...");b++;a.length>b?setTimeout(function(){download_bseequity(a,b,d,k,l,p,g)},1E3):download_bsedata(a,0,d,k,l,p,g)})}else document.getElementById("om").innerHTML+="<br/><font color=red>eq"+c+h+j+"_csv.zip is not present on server</font>",
addlog(g,"eq"+c+h+j+"_csv.zip is not present on server"),b++,a.length>b?setTimeout(function(){download_bseequity(a,b,d,k,l,p,g)},1E3):download_bsedata(a,0,d,k,l,p,g)}}catch(u){document.getElementById("om").innerHTML+="<br/>File is not found for this date: "+c+h+e,addlog(g,"File is not found for this date: "+c+h+e),setTimeout(function(){download_bseequity(a,b,d,k,l,p,g)},1E3)}}
function download_bsedata(a,b,d,k,l,p,g){try{var f=a[b].split("-")[0],h=a[b].split("-")[1],c=a[b].split("-")[2],e=a[b].split("-")[3],j=e.substr(2,2);f.toUpperCase();for(var m="",f=0;f<d.length;f++)"bsedata"==d[f].toString().split(",")[0]&&(m=d[f].toString().split(",")[1]+e+"/SCBSEALL"+c+h+".zip");require("url");require("http");var n=require("fs"),r=require("adm-zip"),q=require("request");q({method:"GET",uri:m,headers:{"User-Agent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",
Referer:"http://www.bseindia.com/markets/equity/EQReports/BhavCopyDebt.aspx?expandable=3","Accept-Encoding":"gzip,deflate,sdch",Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",Cookie:"cookie"}},function(a,b){null!=b?null!=b.statusCode||""!=b.statusCode?!a&&200==b.statusCode?s(b.statusCode):s(404):s(404):s(404)});var s=function(e){for(var f=0;f<d.length;f++)"options"==d[f].toString().split(",")[0]&&d[f].toString().split(",");200==e?(e=n.createWriteStream(k+"SCBSEALL"+c+h+".zip"),
f=q({method:"GET",uri:m,headers:{"User-Agent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",Referer:"http://www.nseindia.com/products/content/all_daily_reports.htm","Accept-Encoding":"gzip,deflate,sdch",encoding:"null",Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*//*;q=0.8",Cookie:"cookie"}}),f.on("error",function(){document.getElementById("om").innerHTML+="<br/>Error occured in downloading SCBSEALL"+c+h+".zip";addlog(g,"Error occured in downloading SCBSEALL"+
c+h+".zip");setTimeout(function(){download_bsedata(a,b,d,k,l,p,g)},1E3)}),f.pipe(e),f.on("end",function(){document.getElementById("om").innerHTML+="<br>SCBSEALL"+c+h+".zip is downloaded...";addlog(g,"SCBSEALL"+c+h+".zip is downloaded...");(new r(k+"SCBSEALL"+c+h+".zip")).extractAllTo(l,!0);document.getElementById("om").innerHTML+="<br>SCBSEALL"+c+h+".zip is extracted...";addlog(g,"SCBSEALL"+c+h+".zip is extracted...");b++;a.length>b?setTimeout(function(){download_bsedata(a,b,d,k,l,p,g)},1E3):setTimeout(function(){process_bseequity(a,
0,d,k,l,p,g)},2E3)})):(document.getElementById("om").innerHTML+="<br/><font color=red>eq"+c+h+j+"_csv.zip is not present on server</font>",addlog(g,"eq"+c+h+j+"_csv.zip is not present on server"),b++,a.length>b?setTimeout(function(){download_bsedata(a,b,d,k,l,p,g)},1E3):setTimeout(function(){process_bseequity(a,0,d,k,l,p,g)},2E3))}}catch(u){document.getElementById("om").innerHTML+="<br/>File is not found for this date: "+c+h+e,addlog(g,"File is not found for this date: "+c+h+e),setTimeout(function(){download_bsedata(a,
b,d,k,l,p,g)},1E3)}}
function download_nsema(a,b,d,k,l,p,g){function f(h){for(var f=0;f<d.length;f++)"options"==d[f].toString().split(",")[0]&&d[f].toString().split(",");f=require("fs");200==h?(h=f.createWriteStream(k+"MA"+e+c+j+".csv"),f=n({method:"GET",uri:m,headers:{"User-Agent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",Referer:"http://www.nseindia.com/products/content/all_daily_reports.htm","Accept-Encoding":"gzip,deflate,sdch",Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",Cookie:"cookie"}}),
f.on("error",function(){document.getElementById("om").innerHTML+="<br/>Error occured in downloading MA"+e+c+j+".csv";addlog(g,"Error occured in downloading MA"+e+c+j+".csv");setTimeout(function(){download_nsema(a,b,d,k,l,p,g)},1E3)}),f.pipe(h),f.on("end",function(){document.getElementById("om").innerHTML+="<br>MA"+e+c+j+".csv is downloaded ..";addlog(g,"MA"+e+c+j+".csv is downloaded ..");b++;a.length>b?setTimeout(function(){download_nsema(a,b,d,k,l,p,g)},1E3):download_nsefii(a,0,d,k,l,p,g)})):(document.getElementById("om").innerHTML+=
"<br/><font color=red>MA"+e+c+j+".csv is not present on server</font>",addlog(g,"MA"+e+c+j+".csv is not present on server"),b++,a.length>b?setTimeout(function(){download_nsema(a,b,d,k,l,p,g)},1E3):download_nsefii(a,0,d,k,l,p,g))}var h=a[b].split("-")[0],c=a[b].split("-")[1],e=a[b].split("-")[2],j=a[b].split("-")[3].substr(2,2);h.toUpperCase();for(var m="",h=0;h<d.length;h++)"nsema"==d[h].toString().split(",")[0]&&(m=d[h].toString().split(",")[1]+"MA"+e+c+j+".csv");var n=require("request");n({method:"GET",
uri:m,headers:{"User-Agent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",Referer:"http://www.nseindia.com/products/content/all_daily_reports.htm","Accept-Encoding":"gzip,deflate,sdch",Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",Cookie:"cookie"}},function(a,b){null!=b?null!=b.statusCode||""!=b.statusCode?!a&&200==b.statusCode?f(b.statusCode):f(404):f(404):f(404)})}
function download_nsefii(a,b,d,k,l,p,g){function f(f){var m=require("fs");200==f?(f=p.replace(/std_csv/g,"reports"),m=m.createWriteStream(f+"fii_stats_"+c+"-"+h+"-"+e+".xls"),f=n({method:"GET",uri:j,headers:{"User-Agent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",Referer:"http://www.nseindia.com/products/content/all_daily_reports.htm","Accept-Encoding":"gzip,deflate,sdch",Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
Cookie:"cookie"}}),f.on("error",function(){document.getElementById("om").innerHTML+="<br/>Error occured in downloading fii_stats_"+c+"-"+h+"-"+e+".xls";addlog(g,"Error occured in downloading fii_stats_"+c+"-"+h+"-"+e+".xls");setTimeout(function(){download_nsefii(a,b,d,k,l,p,g)},1E3)}),f.pipe(m),f.on("end",function(){document.getElementById("om").innerHTML+="<br>fii_stats_"+c+"-"+h+"-"+e+".xls is processed ..";addlog(g,"fii_stats_"+c+"-"+h+"-"+e+".xls is processeded ..");b++;a.length>b?setTimeout(function(){download_nsefii(a,
b,d,k,l,p,g)},1E3):(Ext.getCmp("pbar3").updateProgress(0),process_nsema(a,0,d,k,l,p,g))})):(document.getElementById("om").innerHTML+="<br/><font color=red>fii_stats_"+c+"-"+h+"-"+e+".xls is not present on server</font>",addlog(g,"fii_stats_"+c+"-"+h+"-"+e+".xls is not present on server"),b++,a.length>b?setTimeout(function(){download_nsefii(a,b,d,k,l,p,g)},1E3):(Ext.getCmp("pbar3").updateProgress(0),process_nsema(a,0,d,k,l,p,g)))}var h=a[b].split("-")[0];a[b].split("-");var c=a[b].split("-")[2],e=
a[b].split("-")[3];e.substr(2,2);h.toUpperCase();for(var j="",m=0;m<d.length;m++)"nsefii"==d[m].toString().split(",")[0]&&(j=d[m].toString().split(",")[1]+"fii_stats_"+c+"-"+h+"-"+e+".xls");var n=require("request");n({method:"GET",uri:j,headers:{"User-Agent":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11",Referer:"http://www.nseindia.com/products/content/all_daily_reports.htm","Accept-Encoding":"gzip,deflate,sdch",Accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
Cookie:"cookie"}},function(a,b){null!=b?null!=b.statusCode||""!=b.statusCode?!a&&200==b.statusCode?f(b.statusCode):f(404):f(404):f(404)})};
